version: '3'

services:
  db:
    container_name: trpc_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
      PGDATA: ${PGDATA}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - postgresdb

  # pgadmin:
  #   container_name: trpc_pgadmin
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   networks:
  #     - postgresdb

volumes:
  db-data:
  pgadmin-data:

networks:
  postgresdb: